### ISSUE TITLE
How to switch from minified to non-minified code execution

### ISSUE THREAD

**Issue by koenti** [mcsheaj/SPEasyForms#65]
Hi,
I want to use the non-minified version of SPEasyForms.  What are the steps to make this work?  
Using "jquery.SPEasyForms.js" in user custom action seems not enough :).

reason behind my question:
I want to help debugging some issues.  What toolset should I use?
Koen

**Comment by mcsheaj** [comment]
So I've been working on a better version of the page that installs SPEasyForms on sites without using sandboxed solutions, and the new version should help with what you're trying to do.  Get it at:

https://speasyforms.files.wordpress.com/2017/05/speasyformsinstaller.zip

Just drop that aspx file in your Style Library and open it up in the browser.  Click the uninstall button to remove all of the SPEasyForms custom actions.  Then reload the page with ?Debug=true tacked onto the url, i.e.:

[yoursite]/Style Library/SPEasyFormsInstaller.aspx?Debug=true

It is case sensitive on the arguments.  Once you've loaded it with the debug option, hit the install button, and it will reinstall all of the custom actions (this time the debug ones).

Note that if you want to debug on the settings page, you have to hit the Verbose ribbon button.  This will load the debug versions of the scripts regardless of which custom actions are installed.

Joe

**Comment by koenti** [comment]
I used the installer via IE11 --> perfect.  I work further to test SPEasyForms.

fyi: Via Chrome it throws a CSOM error and nothing happens.  From ULS logs:

Exception occured in scope Microsoft.SharePoint.SPUserCustomAction.set_CommandUIExtension. Exception=System.NullReferenceException: Object reference not set to an instance of an object.    
 at Microsoft.SharePoint.SPUserCustomAction.set_CommandUIExtension(String value)    
 at Microsoft.SharePoint.ServerStub.SPUserCustomActionServerStub.SetProperty(Object target, String propName, XmlNode node, ProxyContext proxyContext)    
 at Microsoft.SharePoint.Client.ServerStub.SetPropertyWithMonitoredScope(Object target, String propertyName, XmlNode node, ProxyContext proxyContext)

**Comment by mcsheaj** [comment]
Not really an issue, more of a query.
