### ISSUE TITLE
Managed meta data in read only mode shows term and guid

### ISSUE THREAD

**Issue by LiesUgent** [mcsheaj/SPEasyForms#69]
When I add a state field (type managed meta data) which is read only mode on the form, because it is only changed by a workflow, I can see the term and the GUID.
The GUID is not relevant for the end user. Is it possible to only show the term.
Kind regards.

**Comment by mcsheaj** [comment]
I'll take a look at it.  It shouldn't be that hard to fix.  Finding the time to look at it will be the hard part, but I'll let you know what I find as soon as I can.

Joe

**Comment by mcsheaj** [comment]
Fix has been released in v2018.01 which can be found at [http://speasyforms.intellipointsol.com/](http://speasyforms.intellipointsol.com/)
