### ISSUE TITLE
Is it possible to only show a html snippet in a specific content type?

### ISSUE THREAD

**Issue by LiesUgent** [mcsheaj/SPEasyForms#74]
We have a list with 5 content types. All the fields are added to specific tabs. Only the tabs containing fields for the selected content type are displayed.

Now we want to add two tabs with a specific text in it. We have created two html snippets and added them to the a new tabs container. The html snippets only have to be shown for ONE specific content type.
How can we force this? Now the html snippets are shown in all the content types. 

Thanks in advance!

Lies

**Comment by mcsheaj** [comment]
At the moment, this is not possible without writing some custom code.  I have been asked before to add functionality for conditional visibility of containers, which would satisfy your need, but it would be a pretty big change and I've been too busy to add new features for a while now.  I do think it would be a nice feature to add, but I can't say right now when I might be able to get around to it.

Joe

**Comment by Perneel** [comment]
@mcsheaj, I wonder if it is possible to hide those specific tabs after SPEasyForms is loaded? I thought it would be possible with JSLink, but that gets executed before the initialization of SPEasyForms.

Does SPEasyForms have a 'hook' to execute code when it has been initialized (and the dom is up to date)? So basicly some `onLoaded` method which can be used in JSLink?

**Comment by mcsheaj** [comment]
Hi Perneel,

Yes, it is possible.  I describe how in the final comment of this issue:

[Issue 66: jquery execution](https://github.com/mcsheaj/SPEasyForms/issues/66)

I've always meant to make this easier by providing pre and post rendering hooks in SPEasyForms, but I've never gotten around to it (or remembered it when I was fixing something else).

Joe

**Comment by mcsheaj** [comment]
My bad.  window.spefjQuery.spEasyForms.init is the method that starts the action, but it ends with 4 asynchronous Ajax calls and the rendering actually occurs after they resolve.  If you override window.spefjQuery.spEasyForms.contextReady instead, it's the callback that does the actual rendering after those async calls resolve. 

Joe

**Comment by Perneel** [comment]
@mcsheaj, works like a charm. Thank you very much for the explanation!
