### ISSUE TITLE
Form is being submitted without any validation, SP2013 and Later.

### ISSUE THREAD

**Issue by fsabry** [mcsheaj/SPEasyForms#75]
Hello, I'm facing an issue with the latest version. The form is being submitted and it is bypassing any validation and the empty list item is created.
Thanks

**Comment by mcsheaj** [comment]
What version of SharePoint, and what browser(s)/browser version(s)?

**Comment by mcsheaj** [comment]
I have found and fixed this.  I'm putting together a release for version 2018.02. Should be out within an hour or so.

Joe

**Comment by mcsheaj** [comment]
This issue is fixed in version 2018.02.  And thanks for reporting it.  2018.01 has been downloaded roughly 400 times with this nasty bug in it, but you're the first to report it.
