### ISSUE TITLE
Autocomplete field adapter not show results

### ISSUE THREAD

**Issue by cor315** [mcsheaj/SPEasyForms#76]
Hi, I'm trying to use the autocomplete lookup field adapter and there is no drop down when I start typing the name of an item.

I just wanted to know if this could be related to the fact that I'm using Sharepoint Foundation 2013.

Thanks

**Comment by mcsheaj** [comment]
Hello,

I would have to say no.  My standard test environment for SharePoint 2013 is Foundation, and I haven't had this problem.  What type of list holds your lookup data, and what field type is the lookup field?  Also, how many items are in the lookup list?  Without seeing what's happening in a debugger, it's hard to say what the issue might be.

Joe

**Comment by cor315** [comment]
OK thanks

Just a custom list and the field type is text

The list I was testing with has just under 1000 items.  I just tried with a smaller list and it worked so I guess it was related to the amount of items?  I think I'll close the issue since I probably won't use large lists in production.

Thanks for this project by the way.  I've had a great time playing around with all the options.

**Comment by mcsheaj** [comment]
Ok, but just fyi, I've tested with up to 5000 items without issue.  Since that's the current default list view threshold, I figured that was a reasonable boundary.  So 1000 items shouldn't really be a problem.

Joe
