### ISSUE TITLE
User Custom Actions Placed in every newly created site collection.

### ISSUE THREAD

**Issue by ghost** [mcsheaj/SPEasyForms#77]
Good Afternoon,
We have recently found that any newly created site collection automatically has the user custom actions from the 2015.01.06. These sites do not have the files, the solution, or any other trace of SPeasyForms. This happens in every new site, whether it is a personal self-service created site, a new site in an existing web app, and a new site in a new web app with a new content db. We have searched the 14 and 15 Hives, the server registry, as well as the SharePoint_config Database. Somehow these user custom actions are stuck somewhere we cannot find them, and they only appear in a new content database when a site is created, but not at all before. We noticed that the table entry in the databases uses all primary keys which would indicate it is written directly into the table with referencing another DB table for its data. Any guidance on what could be causing this, or where User Custom Actions are added from when they are intended to be part of new site creation would be greatly helpful.

**Comment by ghost** [comment]
Good Morning Joe,
Thank you for the quick response. I had forgotten to mention that we are on SP2013, but we migrated from 2010 some years ago. Unfortunately, my predecessor is the one who set this stuff up, so I was not here for the implementation or migration. 

As for the possibilities: 
1. I have seen both the older version and installer page version, which is how I was able to focus in on what exactly was happening with the UserCustomActions being added indiscriminately. Based on just that element, it seems unlikely that the issue is tied directly to your solution but rather has somehow latched on to just that portion of your solution. 
2. Luckily I was able to use Notepad++ to screen the files within the hives so I am confident that there hasn't been any unsupported modifications. 
3. I was able to query the databases but only in a targeted capacity, so one thing I will be checking as well now is the event receivers to see if anything is tied in. 
4. Lastly, and from my perspective the only viable possibility beyond unintentional "corruption type" issues tying files together during the migration, is the feature stapling. My team is not aware, of any instances of this however, I am going to focus my investigation on this possibility. 

Again, Thank you for the quick response, and if my added info brings anything to mind, please don't hesitate to share. LOL. Otherwise I will let you know what I find out after investigating the stapling and event receiver possibilities.

Very Respectfully,
Tony

**Comment by ghost** [comment]
Good Morning Joe,
My apologies for the delay in communication, the recent weather has not been kind in our area. That aside, I did some additional testing, where I created a site collection using every Site Template which would work, I did this for both Compatibility Levels 14 and 15. Again our Farm is SP2013. Additionally, I added 2 more sites without any template at all one for each compat level. This gave me a total of 97 site collections. Of those, only the 15 LVL sites were affected, and within them all but one template and the non template sites had the User Custom Actions(UCA). After some comparison and cross reference elimination, I narrowed the possibilities to 45 specific features. One by one I enabled these features and checked for the UCA. I have found that specifically the navigation feature causes these UCA to be created within the site. Either, by enabling the Navigation feature on its own, or when the feature is activated as a dependency as with the Publishing Site Feature. I have yet to identify exactly how the UCA are tied to the activation of the NAV feature, but they also remain once the feature has been disabled as well. 

Please let me know if you have any ideas in regards to this specific connection of UCA and feature. I will continue digging and let you know if I find anything.

Very Respectfully,
Tony

**Comment by mcsheaj** [comment]
Closed for inactivity, but if you're still having this issue let me know and I'll reopen it.
